### ISSUE TITLE
Rotate object on button click

### ISSUE THREAD

**Issue by azmatullah1** [godswearhats/jquery-ui-rotatable#13]
How can I rotate an object while clicking on a button with some predefined angle instead of using the handle? Actually I need both features that user should be able to rotate object (an image etc) through handle by using mouse and also by entering value of angle in text box and clicking on button.

**Comment by godswearhats** [comment]
To set the angle of element with ID 'target' to 1 radian, do this:

`$('#target').data('uiRotatable').angle(1.0)`

Need it in degrees? Let's say you wanted to set it to 30 degrees ...

`$('#target').data('uiRotatable').angle(Math.PI * 30 / 180)`

Combine with the jQuery `bind()` function to do whatever you need.
