### ISSUE TITLE
snap rotate to ShiftKey

### ISSUE THREAD

**Issue by kipsas** [godswearhats/jquery-ui-rotatable#15]
Hello,
I have just used this great widget for a client-side layout designer jquery plugin, and I needed the feature of rotating elements in it. I also needed an additional feature, that Shiftkey snaps the angle on rotate event to the nearest 45 degree. 

I was just wondering if you could use my solution to improve the widget with the following snippet (rotateElement function):

After the row 

        var rotateAngle = mouseAngle - this.mouseStartAngle + this.elementStartAngle;

insert the following: 

        if(event.shiftKey){
            var degree = rotateAngle * (180/Math.PI);
            var closestStep = 0;
            var step = 45; // it could be an input option to the widget
            var dist = degree%360%step;
            var gap = step - Math.abs(dist);

            if(Math.abs(dist) < gap){
                closestStep = (degree - dist) * (Math.PI/180);
            }
            else if(Math.abs(dist) >= gap){
                if(dist < 0){
                    closestStep = degree - gap;
                }
                else if(dist > 0){
                    closestStep = degree + gap;
                }
                else{
                    closestStep = degree;
                }
                closestStep = closestStep * (Math.PI/180);
            }
            rotateAngle = closestStep;
        }

**Comment by godswearhats** [comment]
Fixed in #17 thanks to @rouxguigui
