### ISSUE TITLE
duplicated handle in other version of jquery-ui

### ISSUE THREAD

**Issue by taizan** [godswearhats/jquery-ui-rotatable#16]
Using this script with jquery-ui-1.9.1 the handle is duplicated  when rotating element.
I hide it in rotateElement(); ( Im not sure this is proper way) 

   rotateElement: function(event) {
      ~~~
     $( ".ui-draggable-dragging" , this.element ).hide();
     return false;
  }

**Comment by godswearhats** [comment]
I can't reproduce this error with the latest jquery-ui (1.11.2) so closing for now.
