### ISSUE TITLE
Setting center of rotation

### ISSUE THREAD

**Issue by Snorvarg** [godswearhats/jquery-ui-rotatable#18]
Hi, 
I added some code for setting the center of rotation, and since I am new to github I could not figure out how I helped out in your piece of code here. 

Instead I made a fork, which can be found here: 
https://github.com/Snorvarg/jquery-ui-rotatable

Feel free to use it if you find it usable!

**Comment by godswearhats** [comment]
@Snorvarg there's a pull request button beside your code. Just click it :-)

**Comment by Snorvarg** [comment]
Thank you. I created a pull request, I guess it means you will be able to merge back and/or modify the changes I have made. Please remove my 'modified by' comments, I added them to make it easier for me to later merge in any new release from you.
