### ISSUE TITLE
Is jquery-ui-rotatable works with jQuery 2?

### ISSUE THREAD

**Issue by zephiransas** [godswearhats/jquery-ui-rotatable#27]
With jQuery2, it won't work well for me.

To reproduce the problem, modify demo.html like htis
``` html
<!--
<script src="http://code.jquery.com/jquery-1.11.3.js"></script>
-->
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
```

**Comment by godswearhats** [comment]
What exactly is not working? I have no trouble with jquery-2.1.4.js on either Firefox or Safari.

**Comment by zephiransas** [comment]
Oops. Please disregard what I wrote. 
I just found works well with jQuery2....
