### ISSUE TITLE
The option wheelRotate doesn't seem to work

### ISSUE THREAD

**Issue by abishekrsrikaanth** [godswearhats/jquery-ui-rotatable#31]
I have setup a fiddle http://jsbin.com/gasolo/edit?html,js,output to replicate this issue.
When the option `wheelRotate` is set to false, it still rotates when the wheel is rotated on the element.

**Comment by godswearhats** [comment]
There currently is no option for `wheelRotate`. However, I'll add it now.

**Comment by godswearhats** [comment]
The `wheelRotate` option is not in the release yet. If you want that functionality, you'll need to host the javascript yourself until I push out a new release.
