### ISSUE TITLE
Feature request: Ability to alter angle and return false within rotate callback

### ISSUE THREAD

**Issue by jspath** [godswearhats/jquery-ui-rotatable#32]
It would be great to be able to cancel a rotate by returning false, or provide containment by being able to alter the angle within the rotate callback.

An example of how this might be achieved:
```javascript
    rotateElement: function(event) {
        if (!this.element || this.element.disabled) {
            return false;
        }

        var rotateAngle = this.getRotateAngle(event);

        var previousRotateAngle = this.elementCurrentAngle;
        this.elementCurrentAngle = rotateAngle;

        // Plugins callbacks need to be called first.
        if ( this._propagate("rotate", event) === false ) {
          this.elementCurrentAngle = previousRotateAngle;
          return false;
        }
        var ui = this.ui();
        if ( this._trigger("rotate", event, ui ) == false ) {
          this.elementCurrentAngle = previousRotateAngle;
          return false;
        } else if (ui.angle.current != rotateAngle) {
          rotateAngle = ui.angle.current;
          this.elementCurrentAngle = rotateAngle;
        }

        this.performRotation(rotateAngle);

        if (previousRotateAngle != rotateAngle) {
            this.hasRotated = true;
        }

        return false;
    },
```

This changes how your plugin works a bit, since now rotate is triggered BEFORE the actual rotation.  This is actually more in line with how typical jQuery widgets work.

Anyways, let me know what you think ... I could fork and create a pull request if you are interested.

**Comment by godswearhats** [comment]
I think I understand and I like the idea.

Can you show me how that might look in the code that would call it? i.e. on the web page that was using the widget?

**Comment by jspath** [comment]
Here's an untested example of what I mean:

```javascript
$('#rotate').rotatable({
  start: function(e, ui){

    // don't allow rotate to start
    if ( some_conditional_to_disable_rotate ) {
      return false;
    }

  },
  rotate: function(e, ui){

    // don't allow rotate to take effect
    if ( some_conditional_to_stop_rotate ) {
      return false;
    }

    // contain angle between 0 and 180 degrees
    if ( Math.PI * 1.5 <= ui.angle.current < Math.PI * 2 ) {
      ui.angle.current = 0;
    } else if ( Math.PI < ui.angle.current < Math.PI * 1.5 ) {
      ui.angle.current = Math.PI;
    }

  }
});
```

I also threw in return false support to start as well as drag, as it seems useful.

Like I said, such a change would force rotate to be triggered before performRotation is called, which could cause issues for people.  However, it is more inline with how the standard jQuery widgets work.

**Comment by godswearhats** [comment]
Go ahead and issue a pull request. I'd be fine with releasing this as v1.1.

**Comment by cmwhiting** [comment]
Just putting it out there, that update creates like 8 billion rotation commands.

**Comment by godswearhats** [comment]
Checking in ... are you still interested in doing this?

**Comment by filipjnc** [comment]
I reckon a lot of users would be interested in this feature. Are you planning on a releasing the new version soon? Thanks.

**Comment by JD-Robbs** [comment]
@jspath I noticed you've forked and committed a few changes. Seeing @godswearhats is happy to include the change in v1.1, I wonder if you'd like to send a pull request? :smiley:

**Comment by jspath** [comment]
Sorry, I've been busy with work and life lately and haven't had time to get
around to setting up a pull request.

I'll try to take care of it this week.

I've been using my rotatable modifications for a while now in production
code, and it everything seems to be working.

**Comment by JD-Robbs** [comment]
No problem - didn't mean to be pushy, I merely saw that you've already done some work in your fork. :wink:  

But great to hear it has been working well in production!

**Comment by godswearhats** [comment]
If you can send me a pull request, I will include it in the 1.1 release which I'm aiming to push out on March 1st.

**Comment by jspath** [comment]
Hey, so I am finally getting around to this.

What minification library and settings do you use?

**Comment by godswearhats** [comment]
I use the [closure compiler](http://closure-compiler.appspot.com/) with simple optimization, but that is not really a well-informed choice, more just one of ease of use.

**Comment by jspath** [comment]
I also wanted to fire this._propagate("stop", event); even if hasRotated is false ... is that an acceptable change?

I have some other modifications I made as well, but they are definitely a separate pull request.

**Comment by godswearhats** [comment]
What's the logic behind emitting a "stop"?

**Comment by jspath** [comment]
Our editor displays a grid line behind elements when they are being manipulated.  So we show the grid on start and hide it on stop.

With the new ability to return false to stop the rotation, it's likely you could have started the rotation, but never actually changed the angle, and then the stop event doesn't fire.

**Comment by jspath** [comment]
I could make this a separate pull request as well, if you would like.

**Comment by godswearhats** [comment]
I think it's fine to emit the stop if the start has been fired.

**Comment by godswearhats** [comment]
I've merged your PR and granted you collaborator access to the repo in case you want to add more and/or merge other PRs in the future.

**Comment by jspath** [comment]
I noticed something odd in my rotate callback.  I was trying to convert the radians angle to a 0 to 360 degree value.  My code to do this is:
`
            var degrees = ui.angle.current * 180/Math.PI;
            if ( degrees < 0 ) degrees += 360;`

I noticed some cases where degrees was still negative even after adding 360, which means that the degree value that ui.angle.current * 180/Math.PI was returning was less than -360.  Is that expected?  I cannot reliably reproduce this issue, but it does occur somewhat regularly.

Also, my demo example is not that great ... I want to change the code to:

`            var degrees = (180/Math.PI) *
              (ui.angle.current > 0
               ? ui.angle.current
               : ui.angle.current + 2 * Math.PI);

            if ( degrees > 180 ) {

              if ( degrees > 270 ) {
                degrees = 0;
              } else {
                degrees = 180;
              }

              ui.angle.current = degrees * Math.PI/180;

            }`

This code behaves much nicer in my 0 to 180 demo, tho it does suffer from the angle less than -360 issue occasionally.
