### ISSUE TITLE
Allow ability to provide external custom handle element

### ISSUE THREAD

**Issue by J7mbo** [godswearhats/jquery-ui-rotatable#36]
jQuery UI's draggable provides the ability to specify an external element as a handler for the rotation.

This would be *incredibly* useful for me within jquery-ui-rotatable. Any plans on implementing something like this?

**Comment by godswearhats** [comment]
In `options`, you can specify `handle`. Does that work for what you're wanting to do?

**Comment by godswearhats** [comment]
Closing issue ... if this wasn't the answer you needed, please re-open.
