### ISSUE TITLE
CDN is out of date

### ISSUE THREAD

**Issue by gtk-1235** [godswearhats/jquery-ui-rotatable#37]
Can you upload the newest version to the CDN? I noticed that you can't disable the scroll-wheel in the CDN version.

I love the plugin! Thanks for all your help!

**Comment by godswearhats** [comment]
I'm aiming to push out a new release March 1st.

**Comment by godswearhats** [comment]
Finally got a release out (yes, I'm lazy) so the CDN should update soon.
