### ISSUE TITLE
`angle` option is in not in degrees

### ISSUE THREAD

**Issue by vanderlee** [godswearhats/jquery-ui-rotatable#38]
The current implementation on CDN has an `angle` option that uses radians.
Not degrees, as mentioned in the readme.

**Comment by JD-Robbs** [comment]
I noticed that as well and am currently converting radians and degrees back and forth.  Maybe it's worth implementing something like a `unit` option?

**Comment by godswearhats** [comment]
Hmmm. I'll get this fixed and push it out as part of the March 1st 1.1 release.

**Comment by mkdizajn** [comment]
In my code I added the custom method for easy converting to degrees like this:

```js
Math.degrees = function(radians) {
  return radians * 180 / Math.PI;
};
```

and when I get the value from angle radians with `Math.degrees( ui.angle.current )` 

hth, cheers

**Comment by godswearhats** [comment]
I'm adding both `degrees` and `radians` functions to the API. Both will function like the current `angle` function, for their respective unit.

**Comment by vanderlee** [comment]
Will the `angle` function be changed to work according to the readme (degrees) or as currently implemented (radians)?

**Comment by godswearhats** [comment]
It will be degrees, because people don't think in radians :-)

**Comment by EvilJordan** [comment]
Just making sure... this was not implemented on the current release available to download, right?

**Comment by godswearhats** [comment]
Fixed.
