### ISSUE TITLE
Mouse out is buggy

### ISSUE THREAD

**Issue by ArnabBanerji** [godswearhats/jquery-ui-rotatable#44]
Steps to reproduce:
1. Start rotation by mouse down.
2. Keeping the mouse button down the user moves out of browser window.
3. Release mouse button outside.
4. Enter back to the browser window.

The rotation is still active.

This can be fixed by adding the following on line (Line #165)

rotateElement: function(event) {

if(!event.which){return;}

**Comment by godswearhats** [comment]
Fixed.
