### ISSUE TITLE
wheelRotate: false still rotates the element on wheel move

### ISSUE THREAD

**Issue by yannakyp** [godswearhats/jquery-ui-rotatable#46]
When passing wheelRotate: false in options, moving the wheel still rotates the element.

**Comment by godswearhats** [comment]
Can't reproduce in Firefox or Chrome. Please re-open if you can give me a browser / OS combination where this is broken.

**Comment by AshwinTayson** [comment]
Happens in Chrome - Latest version, Ubuntu Linux 16.04

**Comment by Kompasua** [comment]
Have same problem
Chromium Version 52.0.2743.116 Built on Ubuntu , running on LinuxMint 17.2 (64-bit)
