### ISSUE TITLE
Request: Snap to certain degrees

### ISSUE THREAD

**Issue by DaGLiMiOuX** [godswearhats/jquery-ui-rotatable#51]
Hi!

I don't if it is possible to do it with this plugin, if you will implement it or if I have to manually modify the source code, but what I'm looking for is a way to configure a start degrees and an end degrees values to allow rotation from 3º to 356º (for example), but if it arrives to 0º, rotate to 0º.

This could be usefull if you don't want that the user that will rotate the element has to extrictly rotate the element to 0º. E.g.: when 356º is reached, prevent rotation until it arrives to 0º. If 0º is reached, rotate element to 0º and prevent rotation until it goes again to 3º or 356º. Even if you set `step: 1` and `snap: true` it would be a good implementation, so they can't miss to "reset" the rotation.

Thanks in advance.

Regards,
Daglimioux.

**Comment by godswearhats** [comment]
This is doable with `step: 1` and `snap: true` (although `step: 2` probably works better)
