### ISSUE TITLE
Request: possible to apply this to a div background image?

### ISSUE THREAD

**Issue by kapyaar** [godswearhats/jquery-ui-rotatable#55]
Is it possible to use this on a div background image? idea is to reposition, rotate, resize the div background image right on the webpage dynamically. I found https://github.com/kentor/jquery-draggable-background which is really cool. Was wondering if rotatable could work that way

**Comment by godswearhats** [comment]
No idea if it would work. Have you tried it?

**Comment by godswearhats** [comment]
Closing due to no response.
