### ISSUE TITLE
Request: Resize from all sides

### ISSUE THREAD

**Issue by akshaynarvekar** [godswearhats/jquery-ui-rotatable#57]
I would like the functionality to resize from all four sides of the div.

**Comment by godswearhats** [comment]
Maybe something to ask for jquery-ui team, who own the `resizable()` plugin.

**Comment by akshaynarvekar** [comment]
The jquery-ui resizable() is resizable from all sides, however it is restricted in this plugin.

**Comment by godswearhats** [comment]
Can you give an example (e.g. using jsfiddle) that I can work from to fix?

**Comment by anpjam459** [comment]
How i can use ui-resizable-se icon at right-bottom cornor to rotate ?
Can you give me some idea to group resizable and rotatable to one button ?
