### ISSUE TITLE
Rotation not smooth when container has css tranform scale

### ISSUE THREAD

**Issue by AshwinTayson** [godswearhats/jquery-ui-rotatable#58]
I tried using this plugin and use css transform to apply zooming. After zooming the rotation flickers and doesn't work smoothly.

I have attached a jsfiddle for example
https://jsfiddle.net/pj0fLxdk/

**Comment by godswearhats** [comment]
Which browser are you using, on which OS? The fiddle you linked to seems to work fine for me in Firefox on MacOS X.

**Comment by godswearhats** [comment]
Closing due to no response.
