### ISSUE TITLE
Rotatable + draggable

### ISSUE THREAD

**Issue by ikarius6** [godswearhats/jquery-ui-rotatable#6]
The problem is when you rotate a element, then you try to drag it.. the element make a little jump of position, then drag..... that little jump is big as the rotation angle.... that happens in the DEMO too

http://godswearhats.com/jquery-ui-rotatable/demo.html

With the #target3, if you resize a little your element, then rotate, then drag... the jump of position is clearly visible. I don't know the reason why #target2 works perfectly but in my implementation (same than target2) acts like target3 with the little jump when I try to drag. Help!

---

Seems related to the position:absolute.... position:relative works fine!

**Comment by danielehrhardt** [comment]
When i do it like @godswearhats  said i get this wired problems like you see in the Video:
https://youtu.be/AQqBJRco7VE
