### ISSUE TITLE
How to avoid scrool whell to rotate when hovering and object?

### ISSUE THREAD

**Issue by qimzu** [godswearhats/jquery-ui-rotatable#65]
There is a wheelRotate option but it does not apply to Scroll Whell rotation when hovering. Is there a way to actually disable an object to rotate (with scroll wheel) when hovered?

**Comment by godswearhats** [comment]
Setting `wheelRotate` to `false` is intended to disable scroll wheel rotation of any sort. If that's not the case, can you post some code showing what you're doing, and let me know what browser you're using? Then I can try to diagnose and fix. Thanks!
