### ISSUE TITLE
Image not rotating in center .

### ISSUE THREAD

**Issue by jaxindia7** [godswearhats/jquery-ui-rotatable#67]
var params = {
            // Callback fired on rotation start.
            start: function(event, ui) {
            },
            // Callback fired during rotation.
            rotate: function(event, ui) {
               // if (Math.abs(ui.angle.current > 6)) {
                 console.log("Rotating " + ui.angle.current)
               // }
            },
            // Callback fired on rotation end.
            stop: function(event, ui) {
            },
            // Set the rotation center at (25%, 75%).
            // angle: 0.2,
            rotationCenterX: 25.0,
            rotationCenterY: 75.0,
            transforms: {
                translate: '(50%, 50%)',
                scale: '(2)'
                //any other transforms
            },
        };

  $(document).on('click', '.block-add', function () {

        var a = $(this);
        var src = a.find('img:first').attr('src');
        var elem = $('<div class=""><img src="' + src + '" class="blocks" /></div>');
        $('.block').append(elem);
        elem.draggable();
        elem.rotatable(params).find('.blocks:first').resizable({ handles: "nw, sw, se, ne" });

// When rotating image its rotate from corner point of image .How to fix this ?

**Comment by godswearhats** [comment]
You can use `rotationCenterOffset` to change the rotation point of the element.

```javascript
rotationCenterOffset: {
    top: 10,
    left: 20
}
```
