### ISSUE TITLE
bug with draggable plugin

### ISSUE THREAD

**Issue by wmlgl** [godswearhats/jquery-ui-rotatable#68]
the rotate center was changed after drag end.

**Comment by godswearhats** [comment]
Can you add JSFiddle or a gist that demonstrates the problem please?

**Comment by godswearhats** [comment]
Closing after 3 months, no response.

**Comment by wmlgl** [comment]
http://sandbox.runjs.cn/show/71trxcaq

**Comment by danielehrhardt** [comment]
@wmlgl did you find a fix?

**Comment by patrickbussmann** [comment]
It is already fixed: https://jsfiddle.net/fwv34xux/
