### ISSUE TITLE
Problem with mouse wheel rotate.

### ISSUE THREAD

**Issue by rahulpatel033** [godswearhats/jquery-ui-rotatable#72]
start, stop methods are not called when rotate using mouse wheel.
And how do I call rotate programmatically? Let's say if I have a input box and when I add rotation angle into it how would I change the rotation?

**Comment by rpatelob** [comment]
- 

- [ ] 1.

**Comment by godswearhats** [comment]
The plugin is not designed with that use case in mind. If you have an input box, why not just use a transform after input?

As for callbacks with mouse wheel - I will look into it, but I don't have a lot of time at the moment. Perhaps you'd care to submit a pull request?

**Comment by godswearhats** [comment]
No response after 2 years, closing.
