### ISSUE TITLE
Use target img as handle

### ISSUE THREAD

**Issue by mtwallet** [godswearhats/jquery-ui-rotatable#73]
Hi there,

Please can you tell me if I can use the target element that is being rotated as the handle too?

I have the following markup:

`<div><img /></div>`

I want to rotate the img and use it as the handle at the same time. It appears to work when I reference it as the handle:

`img.attr('data-edit-status', 'rotating').rotatable({
    degrees: currentRotation,
    handle: img,
    stop: function (event, ui) {
        currentRotation = ui.angle.degrees
    }
})`

but when I try and destroy the rotation it fails:

`$('img[data-edit-status="rotating"]').rotatable('destroy')`

Many thanks in advance.

**Comment by godswearhats** [comment]
This wasn't the intended use for the API when it was written. I'm a little surprised it works at all :-) I don't have a lot of time at the moment (my open source time is being spent on another project) but I'm happy to accept pull requests if you are able to work out why `destroy` isn't working and create a fix.

**Comment by godswearhats** [comment]
No further requests for this feature, so closing as "won't fix".
