### ISSUE TITLE
Rotating not working correctly with Dragging

### ISSUE THREAD

**Issue by danielehrhardt** [godswearhats/jquery-ui-rotatable#74]
Hi Guys,

i have some wired Problems with the rotatable Plugin. 
This happens also on the normal demo page.
http://godswearhats.com/jquery-ui-rotatable/demo.html

When i start to drag and then rotate all look fine but when i try it a second or third time the rotation is really wired. Look at the Video:
https://youtu.be/AQqBJRco7VE

I hope someone can fix this.

Thank You,
Daniel

**Comment by patrickbussmann** [comment]
Forget it you're noob!!!!!!!!!

**Comment by patrickbussmann** [comment]
I have the same issue. Please fix @godswearhats 👍

**Comment by danielehrhardt** [comment]
https://github.com/godswearhats/jquery-ui-rotatable/issues/68

**Comment by patrickbussmann** [comment]
https://jsfiddle.net/fwv34xux/

**Comment by danielehrhardt** [comment]
Fixed with Commit https://github.com/godswearhats/jquery-ui-rotatable/commit/bcbadef03ebff144ee07727af40afd4aac65d972
