### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by kglosnicki** [godswearhats/jquery-ui-rotatable#81]
In example of transform parameter there is unnecessary bracket. User should enter transform value without bracket to make it work.

**Comment by godswearhats** [comment]
I'm not entirely sure what you mean? Can you submit a quick PR with the change?

**Comment by sergio0983** [comment]
Instead of: 
```
transforms: {
      translate: '(50%, 50%)',
      scale: '(2)'
      //any other transforms
  }
```

It should be

```
transforms: {
      translate: '50%, 50%',
      scale: '2'
      //any other transforms
  }
```

I think he meant parenthesis, not brackets.

**Comment by godswearhats** [comment]
Fixed, thanks!
