### ISSUE TITLE
Math.abs gives wrong degrees value

### ISSUE THREAD

**Issue by unlocomqx** [godswearhats/jquery-ui-rotatable#82]
[Math.abs](https://github.com/godswearhats/jquery-ui-rotatable/blob/f7841e1893233a582d470d7a2053cab53a3d9437/jquery.ui.rotatable.js#L174) gives the wrong deg result as you can see here
https://jsfiddle.net/unloco/13sgedLn/12/

I don't understand why it was used, I forgot all about trig

**Comment by godswearhats** [comment]
Hahaha, what a fun bug :) Please feel free to submit a PR and I will merge. I'm not actively working on this project any more.

**Comment by unlocomqx** [comment]
Np, I just submitted a PR
