### ISSUE TITLE
Rotatable with Packering

### ISSUE THREAD

**Issue by nickl-** [godswearhats/jquery-ui-rotatable#87]
I was hoping this would work out of the box with [packering](https://packery.metafizzy.co/draggable.html#jquery-ui-draggable), this is not the case. Would be nice to have a library that plugs into jqueryui seamlessly so....

Lets see if we can make it work then shall we, issue opened for attention, suggestions and note keeping.

Some issues so far:
* [x] No rotate indicator in left corner, can't find handle to mouse rotate - fixed css wasn't loaded  
* [ ] Wheel rotate seems to ignore degrees
* [ ] When using snap wheel rotate stops
* [ ] Returns back to normal orientation by packering when moved
* [ ] There also seems to be bigger problems when using with jqueryui 1.12.1 (as a side note)

Here is a [codepen](https://codepen.io/nickl-/pen/jOBvrpW) as an example implementation with draggable, resizable and rotatable. Using jqueryui 1.11.2.

Any suggestions?

**Comment by nickl-** [comment]
Also can't seem to get the example working so there might be more issues then expected.

See [codepen](https://codepen.io/nickl-/pen/RwpYGPz) for example.

**Comment by nickl-** [comment]
Demo works as expected.

See [codepen](https://codepen.io/nickl-/pen/LYWJRRM) for demo.

**Comment by nickl-** [comment]
There exists another project [abdullahpazarbasi/jquery-ui-rotatable](https://github.com/abdullahpazarbasi/jquery-ui-rotatable) which appears to work as expected.

**Comment by godswearhats** [comment]
Cool, looks like someone forked the project. It’s been a few years since
I’ve been working in jQuery.

**Comment by nickl-** [comment]
Always fun to merge forks back too. =)

Thanks for starting the initiative, saved me some pulled out hair.

**Comment by godswearhats** [comment]
No worries. I would be happy to give @abdullahpazarbasi editor/owner access here to merge things back, or point people to that implementation as the most up to date version.
